/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    type: 'group',
    icon: 'heroicons_custom:dashboard',
    children: [
      {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_custom:dashboard',
        link: '/dashboard',
      },
      {
        id: 'manufacturing',
        title: 'Manufacturing',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/manufacturing/dashboard',
      },
    ],
  },
  {
    id: 'sm',
    title: 'Sales Management',
    type: 'group',
    icon: 'heroicons_custom:sales-managment',
    children: [
      {
        id: 'sm.quotes',
        title: 'Quotes',
        type: 'basic',
        icon: 'heroicons_custom:quotes',
        link: '/quotes',
      },
      {
        id: 'sm.projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:home-modern',
        link: '/projects',
      },
      {
        id: 'sm.invoices',
        title: 'Invoices',
        type: 'basic',
        icon: 'heroicons_custom:invoices',
        link: '/invoices',
      },
      {
        id: 'sm.sale-orders',
        title: 'Sale Orders',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/sale-orders',
      },
      {
        id: 'sm.delivery-notes',
        title: 'Delivery Notes',
        type: 'basic',
        icon: 'feather:truck',
        link: '/delivery-notes',
      },
    ],
  },
  {
    id: 'bc',
    title: 'Business Contacts',
    type: 'group',
    icon: 'heroicons_custom:business-contacts',
    children: [
      {
        id: 'clients',
        title: 'Clients',
        type: 'basic',
        icon: 'heroicons_custom:clients',
        link: '/clients/all-clients',
      },
      {
        id: 'suppliers',
        title: 'Suppliers',
        type: 'basic',
        icon: 'heroicons_custom:suppliers',
        link: '/suppliers',
      },
      {
        id: 'consignors',
        title: 'Consignors',
        type: 'basic',
        icon: 'heroicons_solid:user-minus',
        link: '/consignors',
      },
    ],
  },
  {
    id: 'stocks',
    title: 'Stocks',
    type: 'group',
    icon: 'heroicons_custom:stocks',
    children: [
      {
        id: 'stocks.stocks',
        title: 'Stock Overview',
        type: 'basic',
        icon: 'heroicons_custom:stock-overview',
        link: '/stocks',
      },
      {
        id: 'stocks.po',
        title: 'Purchase Orders',
        type: 'basic',
        icon: 'heroicons_custom:purchase-orders',
        link: '/purchase-orders',
      },
      {
        id: 'stocks.grv',
        title: 'GRV',
        type: 'basic',
        icon: 'heroicons_custom:grv',
        link: '/grv',
      },
      {
        id: 'stocks.inter-branch-transfers',
        title: 'Inter Branch Transfers',
        type: 'basic',
        icon: 'heroicons_custom:inter-branch',
        link: '/inter-branch-transfers',
      },
    ],
  },
  {
    id: 'manufacturing',
    title: 'Manufacturing',
    type: 'group',
    icon: 'heroicons_custom:machines',
    children: [
      {
        id: 'manufacturing',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:chart-bar-square',
        link: '/manufacturing/dashboard',
      },
      {
        id: 'machines',
        title: 'Machines',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/machines',
      },
      {
        id: 'ccl',
        title: 'Completed Product Lists',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/completed-products',
      },
      {
        id: 'prod-transactions',
        title: 'Product Transaction',
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/product-transactions',
      },
    ],
  },
];
export const compactNavigation: FuseNavigationItem[] = [];
export const futuristicNavigation: FuseNavigationItem[] = [];
export const horizontalNavigation: FuseNavigationItem[] = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    type: 'group',
    icon: 'heroicons_custom:dashboard',
    children: [
      {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_custom:dashboard',
        link: '/dashboard',
      },
      {
        id: 'manufacturing',
        title: 'Manufacturing',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/manufacturing/dashboard',
      },
    ],
  },
  {
    id: 'sm',
    title: 'Sales Management',
    type: 'group',
    icon: 'heroicons_custom:sales-managment',
    children: [
      {
        id: 'sm.quotes',
        title: 'Quotes',
        type: 'basic',
        icon: 'heroicons_custom:quotes',
        link: '/quotes',
      },
      {
        id: 'sm.projects',
        title: 'Projects',
        type: 'basic',
        icon: 'heroicons_outline:home-modern',
        link: '/projects',
      },
      {
        id: 'sm.invoices',
        title: 'Invoices',
        type: 'basic',
        icon: 'heroicons_custom:invoices',
        link: '/invoices',
      },
      {
        id: 'sm.sale-orders',
        title: 'Sale Orders',
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/sale-orders',
      },
      {
        id: 'sm.delivery-notes',
        title: 'Delivery Notes',
        type: 'basic',
        icon: 'feather:truck',
        link: '/delivery-notes',
      },
    ],
  },
  {
    id: 'bc',
    title: 'Business Contacts',
    type: 'group',
    icon: 'heroicons_custom:business-contacts',
    children: [
      {
        id: 'clients',
        title: 'Clients',
        type: 'basic',
        icon: 'heroicons_custom:clients',
        link: '/clients/all-clients',
      },
      {
        id: 'suppliers',
        title: 'Suppliers',
        type: 'basic',
        icon: 'heroicons_custom:suppliers',
        link: '/suppliers',
      },
      {
        id: 'consignors',
        title: 'Consignors',
        type: 'basic',
        icon: 'heroicons_solid:user-minus',
        link: '/consignors',
      },
    ],
  },
  {
    id: 'stocks',
    title: 'Stocks',
    type: 'group',
    icon: 'heroicons_custom:stocks',
    children: [
      {
        id: 'stocks.stocks',
        title: 'Stock Overview',
        type: 'basic',
        icon: 'heroicons_custom:stock-overview',
        link: '/stocks',
      },
      {
        id: 'stocks.po',
        title: 'Purchase Orders',
        type: 'basic',
        icon: 'heroicons_custom:purchase-orders',
        link: '/purchase-orders',
      },
      {
        id: 'stocks.grv',
        title: 'GRV',
        type: 'basic',
        icon: 'heroicons_custom:grv',
        link: '/grv',
      },
      {
        id: 'stocks.inter-branch-transfers',
        title: 'Inter Branch Transfers',
        type: 'basic',
        icon: 'heroicons_custom:inter-branch',
        link: '/inter-branch-transfers',
      },
      {
        id: 'stocks.inter-branch-transfers',
        title: 'Outsourced Products',
        type: 'basic',
        icon: 'heroicons_custom:inter-branch',
        link: '/outsourced-products',
      },
    ],
  },
  {
    id: 'manufacturing',
    title: 'Manufacturing',
    type: 'group',
    icon: 'heroicons_custom:machines',
    children: [
      {
        id: 'manufacturing',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/manufacturing/dashboard',
      },
      {
        id: 'machines',
        title: 'Machines',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/machines',
      },
      {
        id: 'ccl',
        title: 'Completed Cutting Lists',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/completed-cutting-lists',
      },
      {
        id: 'prod-transactions',
        title: 'Product Transaction',
        type: 'basic',
        icon: 'heroicons_custom:machines',
        link: '/product-transactions',
      },
    ],
  },
];
